
/*
 * Problem 2 http://projecteuler.net/problem=2
 * Each new term in the Fibonacci sequence is generated by adding the 
 * previous two terms. By starting with 1 and 2, the first 10 terms 
 * will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do 
 * not exceed four million, find the sum of the even-valued terms.
 */

object problem2 {

  def main(args: Array[String]): Unit = {
    println(sumeveninfiboseq(4000000))
  }

  def fibo(n: Int): Int = {
    if (n < 2) n else fibo(n - 1) + fibo(n - 2)
  }

  def sumeveninfiboseq(n: Int): Int = {
    var thesum = 0
    var i = 1
    var f = 0
    do {
      f = fibo(i)
      thesum += (if (f % 2 == 0) f else 0)
      i += 1
    } while (f < n)

    return thesum
  }

}